name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
  paths:
      - 'dotnet/helloworld/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: helloworlddotnet
          runtime: dotnet3
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          entry_point: HelloWorld.Function

      - name: Make the URL Aunthenticated
        run: |
          gcloud functions add-iam-policy-binding helloworlddotnet --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: Test the Url
        run: curl "${{ steps.deploy.outputs.url }}"