name: Deploy .NET Core Function
on:
  push:
    branches: [ main ]
    paths:
      - 'dotnet/helloworld/**'

jobs:
  job_name:
    uses: oliveiracdz/cf-mono-repo/.github/workflows/deployFunction.yml@main
    with:
      function_name: helloworlddotnet
      runtime: dotnet3
      entrypoint: HelloWorld.Function
      source_dir: dotnet/helloworld
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}
