name: Deploy .NET Core Function
on:
  push:
    branches: [ main ]
    paths:
      - 'dotnet/helloworld/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    uses: paulofoliveira/cf-mono-repo/.github/workflows/deployFunction.yml@main
    with:
      function_name: helloworlddotnet
      runtime: dotnet3
      entrypoint: HelloWorld.Function
      source_dir: dotnet/helloworld
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}
