name: Deploy Python Function
on:
  push:
    branches: [ main ]
    paths:
      - 'python/helloworld/**'
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   
jobs:
  deploy:
    uses: paulofoliveira/cf-mono-repo/.github/workflows/deployFunction.yml@main
    with:
      function_name: helloworldpython
      runtime: python37
      entrypoint: hello
      source_dir: python/helloworld
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}
